Arrival_rates:
  Class 0:
  - 5.0
  - 2.0
  - 4.0
  Class 1:
  - 3.0
  - 7.0
  - 4.0
Number_of_classes: 2
Number_of_nodes: 3
Number_of_servers:
- 8
- 6
- 6
Service_rates:
  Class 0:
  - - Exponential
    - 8.0
  - - Exponential
    - 9.0
  - - Exponential
    - 6.0
  Class 1:
  - - Exponential
    - 5.0
  - - Exponential
    - 4.0
  - - Exponential
    - 9.0
Simulation_time: 2000
Neighbours_matrices:
  Class 0:
  - - True
    - False
    - True
  - - True
    - True
    - True
  - - False
    - True
    - True
  Class 1:
  - - True
    - True
    - True
  - - False
    - True
    - True
  - - True
    - True
    - False
Exit_rates:
  Class 0:
  - 0.1
  - 0.2
  - 0.1
  Class 1:
  - 0.0
  - 0.4
  - 0.0
Action_selection_parameter: 0.6
Learning_rate: 0.1
Discount_rate: 0.9