language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install coveralls
script:
  - python doctests.py
  - coverage run --source=ciw -m unittest discover ciw
  - pip uninstall -y ciw
  - pip install ciw
after_success: coveralls
