language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/.hypothesis

install:
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install coveralls
  - pip install sphinx
script:
  - cd docs; make html
  - cd ..
  - python doctests.py
  - coverage run --source=ciw -m unittest discover ciw
  - pip uninstall -y ciw
  - pip install ciw
after_success: coveralls
