Arrival_rates:
  Class 0:
  - 2.0
  - 3.0
Number_of_classes: 1
Number_of_nodes: 2
Number_of_servers:
- 1
- 1
Service_rates:
  Class 0:
  - - Exponential
    - 7.0
  - - Exponential
    - 12.0
Simulation_time: 2000
Transition_matrices:
  Class 0:
  - - 0.1
    - 0.5
  - - 0.3
    - 0.3