Arrival_rates:
  Class 0:
  - 22.0
  - 20.0
Number_of_classes: 1
Number_of_nodes: 2
Number_of_servers:
- 2
- 2
Queue_capacities:
- 2
- 3
Service_rates:
  Class 0:
  - - Exponential
    - 7.0
  - - Exponential
    - 7.0
Simulation_time: 2500
Transition_matrices:
  Class 0:
  - - 0.2
    - 0.2
  - - 0.2
    - 0.2
